language: csharp
mono: none
dotnet: 1.0.0-preview2-003121
dist: trusty
sudo: required

install:
  # Display dotnet version info
  - which dotnet;
    if [ $? -eq 0 ]; then
      echo "Using dotnet:";
      dotnet --info;
    else
      echo "dotnet.exe not found"
      exit 1;
    fi


script:  
  - chmod u+x ./build.sh
  - ./build.sh
